In [65]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import MinMaxScaler

### Data normalization

In [66]:
# Loading the dataset from GOOG.csv file
dataframe = pd.read_csv('GOOG.csv')

## Data Analysis portion

# print the dimensions of the Dataframe
print(dataframe.columns.shape)

#print the data types that can be pulled from the entire dataset
print(dataframe.info())

# print the dataset - no need to group by because the values in each row is unique
print(dataframe)

# pull relevant data from dataset (in this case we are pulling the Open, High, Low, Close and Adj Close values from our dataframe)
adjClosedata = dataframe.values[:, 1:6]

# Instantiate the scaler and transform the data
scaler = MinMaxScaler()
scaled = scaler.fit_transform(adjClosedata)

print("Scaled Dataset", scaled)


Scaled Dataset [[0.02178077 0.02218961 0.0222653  0.02321884 0.02321884]
 [0.02340614 0.02229449 0.02292175 0.02281891 0.02281891]
 [0.02241918 0.02303213 0.02290912 0.02406531 0.02406531]
 ...
 [0.92136283 0.92917453 0.93113632 0.93335322 0.93335322]
 [0.91172569 0.92386149 0.91428695 0.9128285  0.9128285 ]
 [0.90637076 0.9085342  0.87980986 0.88062476 0.88062476]]
